// filepath: src/app/layout.tsx
import { ReduxProvider } from "@/lib/redux/provider"; // Create this file
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EduAssist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        data-new-gr-c-s-check-loaded="14.1233.0"
        data-gr-ext-installed=""
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
